# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import ssl_parse.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название сертификата')),
                ('ogrn', models.TextField(null=True, verbose_name='ОГРН')),
                ('inn', models.TextField(null=True, verbose_name='ИНН')),
                ('snils', models.TextField(null=True, verbose_name='СНИЛС')),
                ('ogrnip', models.TextField(null=True, verbose_name='ОГРНИП')),
                ('organization_name', models.TextField(default='', verbose_name='Организация')),
                ('street_address', models.TextField(default='', verbose_name='Адрес')),
                ('locality_name', models.TextField(default='', verbose_name='Местоположение')),
                ('state_or_province_name', models.TextField(default='', verbose_name='Регион')),
                ('country_name', models.TextField(default='', verbose_name='Страна')),
                ('given_name', models.TextField(default='', verbose_name='Имя, Отчество')),
                ('surname', models.TextField(default='', verbose_name='Фамилия')),
                ('common_name', models.TextField(default='', verbose_name='Название')),
                ('email_address', models.TextField(default='', verbose_name='Электронный адрес')),
                ('serial_number', models.IntegerField(null=True, verbose_name='Серийный номер')),
                ('file_certificate', models.FileField(upload_to=ssl_parse.models.Certificate.file_load, verbose_name='Файл сертификата')),
            ],
            options={
                'verbose_name_plural': 'Сертификаты',
                'verbose_name': 'Сертификат',
                'db_table': 'cert_data',
            },
        ),
    ]
